main_category:
  - politics
  - economy
  - international
  - society
  - culture
  - entertainment
  - sports

url:
  chosun: 
    main: https://www.chosun.com
    list_endpoint: 
  joongang: 
    main: https://www.joongang.co.kr
    list_endpoint:
  donga: 
    main: https://www.donga.com
    list_endpoint: /news
  seoul: 
    main: https://www.seoul.co.kr
    list_endpoint: /news/newsList.php?section=
  khan: 
    main: https://www.khan.co.kr
    list_endpoint: 
  maeil: 
    main: https://news.imaeil.com
    list_endpoint: 
  hani: 
    main: https://www.hani.co.kr
    list_endpoint: /arti
  hankook:
    main: https://hankookilbo.com
    list_endpoint: /News