chosun: https://www.chosun.com/
joongang: https://www.joongang.co.kr/
donga: https://www.donga.com/news/
seoul: https://www.seoul.co.kr/news/newsList.php?section=politics
khan: https://www.khan.co.kr/
maeil: https://news.imaeil.com/
hani: https://www.hani.co.kr/arti/
hankook: https://hankookilbo.com/News